FROM python:alpine

# Встановити робочу директорію раніше для оптимізації кешування
WORKDIR /app

# Встановити залежності під користувачем root
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Скопіювати main.py
COPY main.py .

# Add and enable a new user після інсталяції залежностей
RUN adduser -D tgram && addgroup boty && adduser tgram boty

# Переключитись на менш привілейованого користувача
USER tgram

# Запуск програми
CMD ["python", "main.py"]